import Head from 'next/head';
import {v4 as uuidv4} from "uuid";
import React,{useState,useContext} from "react";

import RecipeList from './conponents/RecipeList';

const RecipeContext = React.createContext();

export default function Home() {
  
  const[recipes,setRecipes]=useState();
  
  const contextValues=
  {
    /* createNewRecipe */
  }

  function createNewRecipe()
  {
    const newRecipe=
    {
      id:uuidv4(),
      name:'',
      servings:'',
      cookTime:'',
      instructions:'',
      ingredients:[
        {
          id:uuidv4(),
          name:'',
          amount:''
        }
      ]
    }

    recipes ? setRecipes([...recipes,newRecipe]):setRecipes([newRecipe])
  }

  return (
    <div>
      <Head>
        <title>Fancy Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,900;1,100&family=Manrope:wght@200;300;400;500;700;800&family=Silkscreen&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RecipeContext.Provider value={contextValues}>
          <div className="recipes-container">
            {recipes && <RecipeList recipes={recipes} />}
          </div>
          <button onClick={createNewRecipe}>add recipe</button>
        </RecipeContext.Provider>
      </main>
    </div>
  );
}
